############################
## CHANGE THESE
############################

baseURL: "https://patrickpulfer.github.io/hugo-qubtTemplate"
title: hugo-qubtTemplate

############################
## MISC
############################

enableEmoji: true
disableKinds: ["taxonomy", "term"]
languageCode: "en-us"
enableRobotsTXT: true
